[tools]
bun = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
pipx = "latest"
pnpm = "latest"
python = "3.14.1"
stylua = "latest"
terraform = "1.14.1"
zellij = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
